models:
  - username: Lala
    notificationDate: 2020-06-10T11:29:55.854Z
  - username: Tata
    notify: 1
    record: false
    notificationDate: 2020-06-10T11:24:33.308Z
  - username: Lala
    notify: 1
    notificationDate: 2020-06-15T10:42:25.771Z
  - username: Toto
    notify: 1
    notificationDate: 2020-06-15T10:42:25.744Z
  - username: ferre
destinationPath: product
