models:
  - username: Lala
    notificationDate: 2020-06-10T11:29:55.854Z
  - username: Tata
    notify: 0
    notificationDate: 2020-06-10T11:24:33.308Z
  - username: Lala
    notify: 0
    notificationDate: 2020-06-12T10:39:54.058Z
  - username: Toto
    notify: 1
    notificationDate: 2020-06-12T10:39:54.034Z
destinationPath: product
