models:
  - username: Lala
    notificationDate: 2020-06-10T11:29:55.854Z
  - username: Tata
    notify: 1
    record: false
    notificationDate: 2020-06-10T11:24:33.308Z
  - username: Lala
    notify: 1
    notificationDate: 2020-06-22T10:34:19.459Z
  - username: toto
    notify: 1
  - username: ferre
  - username: toao
    notify: 1
destinationPath: product
