models:
  - username: Lala
    notificationDate: 2020-06-10T11:29:55.854Z
  - username: Tata
    notify: 0
    notificationDate: 2020-06-10T11:24:33.308Z
  - username: Lala
    notify: 1
    notificationDate: 2020-06-11T08:17:52.951Z
  - username: Toto
    notify: 0
    notificationDate: 2020-06-11T08:17:52.928Z
destinationPath: product
